# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31166b745da837cda25a1eff3a0c24e1cfab68e41e0c842de273e544d7dcb4e0e25cfb4d25a9f4ec861d1a9d940e64dfd3c5a3e89c98392a3d10025e838b1993

test:
  secret_key_base: 00f128d4e887fb9ff6ac3042f903a8b572b7ea7324e1c264b2dc698e77bc7df916b1c08c3aaea023e8ee617574bb9a558d31fcf4e510740a4d3d48ccc72662d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
